server:
  port: 8761
spring: 
  application:
    name: spring-msg-server
eureka:
  server:
    enable-self-preservation: false
  client: 
    fetch-registry: false
    register-with-eureka: false
    
    
